name: upper-build

on:
  push:
    paths:
      - ".github/workflows/upper-build.yml"
      - "./upper"

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    name: go-build
    steps:
      - run: ls -al
      - uses: actions/checkout@v4
      - run: ls -al

      - run: go version
      - uses: actions/setup-go@v5
        with:
          # go-version: "1.22"
          go-version-file: ./upper/go.mod
          cache-dependency-path: ./upper/go.sum

      - run: go mod download
        working-directory: upper
      - run: |
          ls -al
          go build
          ls -al
          go test
          ./upper foo the bar
        working-directory: upper
        name: go-build-and-test
